# log path
log:
    windows.filePath: D:\local-repos\BasicCoreJava\src\main\resources\log
    macOs.filepath: /Users/willisbai/GitRepo/BasicCoreJava/src/main/resources/log
    linux.filepath: #TODO

# supported file suffixes，枚举：.md，.txt，
file:
    suffix: .md