# 内置tomcat容器配置
server:
    port: 5050

# 是否开启定时任务
enable:
    scheduling: false

spring:
    # 使用thymeleaf模板引擎
    thymeleaf:
        prefix: classpath:/template/view
        suffix: .html
        mode: HTML # HTML:Thymeleaf检查html格式很严格; LEGACYHTML5：不严格检查html语法
        encoding: UTF-8
        servlet:
            content-type: text/html
        # 为便于测试，在开发时需要关闭缓存
        cache: false
    # 集成redis
    redis:
        host: 127.0.0.1
        port: 6379
        password:

    # 集成postgresql database(最新版)
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: rrsn
        driver-class-name: org.postgresql.Driver
        ## hikari数据源配置
        # 数据源类型
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            #连接池名称，默认HikariPool-1
            pool-name: WillisHikariPool
            ##最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
            maximum-pool-size: 12
            #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
            connection-timeout: 60000
            #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
            minimum-idle: 10
            #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒
            #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
            idle-timeout: 500000
            #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
            max-lifetime: 540000
            #连接测试查询
            connection-test-query: SELECT 1

#mybatis-plus配置
mybatis-plus:
    ## xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper所对应的 XML文件位置）
    mapper-locations: classpath:/**/*Mapper.xml
    type-aliases-package: com.web.entity
    global-config:
      db-config:
          id-type: auto
    configuration:
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
        map-underscore-to-camel-case: true
