server:
    port: 5050

#### Configurations for JavaLogDemo -->com.beijingwujian.JavaLogDemo####Start####
javaLogDemo:
    log:
        windows_file_path: D:\local-repos\BasicCoreJava\src\main\resources\log
        macOs_file_path: /Users/willisbai/GitRepo/BasicCoreJava/src/main/resources/log
        linux_file_path: #TODO

    # supported file suffixes，枚举：.md，.txt，.java（根据已提供的代码模板，生成）
    file:
        suffix: .md
#### Configurations for JavaLogDemo -->com.beijingwujian.JavaLogDemo####End####